// هذا الملف يتم إنشاؤه تلقائياً. لا تقم بتعديله مباشرة.
// This file is automatically generated. Do not edit it directly.
// استيراد المكتبات المطلوبة
// Import required libraries
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// الحصول على عنوان URL الخاص بـ Supabase من متغيرات البيئة
// Get Supabase URL from environment variables
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// الحصول على المفتاح القابل للنشر الخاص بـ Supabase من متغيرات البيئة
// Get Supabase publishable key from environment variables
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// استيراد عميل supabase بهذه الطريقة:
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// إنشاء وتصدير عميل Supabase مع إعدادات المصادقة
// Create and export Supabase client with auth settings
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,  // استخدام localStorage للتخزين - Use localStorage for storage
    persistSession: true,  // الحفاظ على الجلسة - Persist session
    autoRefreshToken: true,  // تحديث الرمز المميز تلقائياً - Auto refresh token
  }
});